name: IIS DSX Import Pipeline

on:
  push:
    branches: [ dev, uat, sit, perf, prod ]

jobs:
  build:
    runs-on: self-hosted
    environment: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: Copy DSX file to artifact directory
        run: |
          mkdir -p artifacts
          cp IIS/ds_package/*.dsx artifacts/

      - name: Upload DSX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsx-package
          path: artifacts/*.dsx
          retention-days: 30

      - name: Copy files to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "artifacts/*.dsx"
          target: "/tmp/DSBuild"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            hostname -f
            mkdir -pv /tmp/DSBuild
